# Specifies labels to apply to pull requests in Project Mu repositories based on regular expressions.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/github/issue-labeler

# Maintenance: Keep labels organized in ascending alphabetical order - easier to scan, identify duplicates, etc.

rules:
  - name: Backport
    conditions:
      - type: regex
        pattern: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Backport to release branch\\?'
    labels:
      - type:backport

  - name: Breaking Change
    conditions:
      - type: regex
        pattern: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Breaking change\\?'
    labels:
      - impact:breaking-change

  - name: Documentation
    conditions:
      - type: regex
        pattern: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Includes documentation\\?'
    labels:
      - type:documentation

  - name: Non-Functional Impact
    conditions:
      - type: regex
        pattern: '\\s*-\\s*(?![x\nX])\\s*\\] Impacts functionality\\?'
    labels:
      - impact:non-functional

  - name: Security Impact
    conditions:
      - type: regex
        pattern: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Impacts security\\?'
    labels:
      - impact:security

  - name: Testing Impact
    conditions:
      - type: regex
        pattern: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Includes tests\\?'
    labels:
      - impact:testing

  - name: Auto Backport Filesync, Dependabot
    type: "pull_request"
    conditions:
      - authors: ["dependabot[bot]","mu-automation"]
      - type: repo
        pattern: '^(mu_basecore|mu_tiano_plus|mu_silicon_arm_tiano|mu_silicon_intel_tiano|mu_plus|mu_oem_sample)$'
    labels:
      - type:backport
