# Specifies labels to apply to pull requests in Project Mu repositories based on regular expressions.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/github/issue-labeler

# Maintenance: Keep labels organized in ascending alphabetical order - easier to scan, identify duplicates, etc.
version: 1
issues: False

labels:
  - label: type:backport
    body: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Backport to release branch\\?'

  - label: impact:breaking-change
    body: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Breaking change\\?'


  - label: type:documentation
      body: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Includes documentation\\?'

  - label: impact:non-functional
      body: '\\s*-\\s*(?![x\nX])\\s*\\] Impacts functionality\\?'

  - label: impact:security
    body: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Impacts security\\?'

  - label: impact:testing
    body: '\\s*-\\s*\\[\\s*[x\nX]\\s*\\] Includes tests\\?'

  - label: type:backport
    type: "pull_request"
    authors: ["dependabot[bot]","mu-automation"]
    base-branch: "dev/*"

